### ISSUE TITLE
miss some apis

### ISSUE THREAD

**Issue by chenqinghaix** [microsoft/MAPIStubLibrary#21]
Compared to the old version, some API interfaces are missing, such as:
1. StubUtils. cpp:
HMODULE LoadRegisteredMapiClient (LPCWSTR pwzProviderOverride)
HMODULE LoadMAPIFromSystemDir()
Can I use any new method to replace the above two methods?
2. MapiStudbLibrary.cpp:
DEFINE_ STUB_ FUSION_ 5 (LINKAGE-EXTERN_C, ULONG, FAR PASCAL,
MAPISendMailW, "MAPISendMailW",
LHANDLE, ULONG_ PTR, lpMapiMessage W, FLAGS, ULONG, (ULONG) MAPI_ E_ CALL_ FAILED
In the new version, only MAPISendMail is available, which will result in sending data that cannot be encoded with Unicode, causing some special characters to not be sent properly.

**Comment by stephenegriffin** [comment]
1. LoadRegisteredMapiClient/LoadMAPIFromSystemDir were support/helper functions that were eliminated in refactoring that split the "get a path" logic from the "load from the path" logic. Neither function was intended for external use.

LoadMAPIFromSystemDir was replaced by GetMAPISystemDir.
LoadRegisteredMapiClient was replaced by GetHKeyMapiClient and GetMAPIPaths.
2. If you submit a PR on this I can review it.

Thanks!
